# Generated by Django 2.1.7 on 2019-05-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZhiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_url', models.CharField(max_length=100, verbose_name='热榜网址')),
                ('question', models.CharField(max_length=30, verbose_name='新闻题目')),
                ('answer', models.TextField()),
            ],
        ),
    ]
