# Generated by Django 2.1.7 on 2019-05-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_url', models.CharField(max_length=100, verbose_name='热榜网址')),
                ('question', models.CharField(max_length=30, verbose_name='新闻题目')),
            ],
        ),
        migrations.RemoveField(
            model_name='zhiinfo',
            name='info_url',
        ),
        migrations.AlterField(
            model_name='zhiinfo',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.ZhihuUrl'),
        ),
    ]
