# Generated by Django 2.1.7 on 2019-05-11 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zhihu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhihuinfo',
            name='info',
            field=models.TextField(default=1, verbose_name='知乎回答'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='zhihuinfo',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhihu.ZhihuAnswer', verbose_name='关联回答个数'),
        ),
    ]
