# Generated by Django 2.1 on 2019-05-14 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.CharField(max_length=500, verbose_name='微博评论内容')),
                ('author_name', models.CharField(max_length=150, verbose_name='评论的用户名字')),
                ('author_description', models.CharField(max_length=200, verbose_name='评论的用户个人描述')),
                ('author_profile', models.CharField(max_length=200, verbose_name='评论的用户头像链接')),
                ('author_url', models.CharField(max_length=200, verbose_name='评论的用户个人中心链接')),
                ('created_at', models.CharField(max_length=50, verbose_name='微博评论时间')),
                ('write_at', models.DateTimeField(auto_now_add=True, verbose_name='评论写入数据库时间')),
            ],
        ),
        migrations.CreateModel(
            name='MbImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=200, verbose_name='微博图片链接地址')),
            ],
        ),
        migrations.CreateModel(
            name='MicroBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_url', models.CharField(max_length=200, verbose_name='微博链接')),
                ('micro_blog_id', models.CharField(max_length=100, unique=True, verbose_name='微博ID')),
                ('content', models.TextField(verbose_name='微博内容')),
                ('subject', models.CharField(max_length=200, null=True, verbose_name='微博主题')),
                ('video_url', models.CharField(max_length=200, null=True, verbose_name='微博视频链接')),
                ('video_count', models.PositiveIntegerField(null=True, verbose_name='微博视频观看次数')),
                ('created_at', models.CharField(max_length=50, verbose_name='创建时间')),
                ('write_at', models.DateTimeField(auto_now_add=True, verbose_name='写入数据库时间')),
                ('comment_count', models.PositiveIntegerField(verbose_name='微博评论数量')),
                ('like_count', models.PositiveIntegerField(default=0, verbose_name='微博点赞数量')),
                ('transmit_count', models.PositiveIntegerField(default=0, verbose_name='微博转发数量')),
                ('author', models.CharField(max_length=150, verbose_name='微博作者名称')),
                ('author_description', models.CharField(max_length=300, verbose_name='微博作者描述')),
                ('author_profile', models.CharField(max_length=200, verbose_name='微博作者头像')),
                ('author_url', models.CharField(max_length=200, verbose_name='微博作者链接')),
                ('source', models.CharField(max_length=50, verbose_name='微博来源：如iPhone')),
            ],
            options={
                'ordering': ['write_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='专题名称')),
                ('desc', models.CharField(max_length=300, null=True, verbose_name='专题描述')),
                ('midtext', models.CharField(max_length=100, null=True, verbose_name='专题阅读、讨论量')),
                ('downtext', models.CharField(max_length=100, null=True, verbose_name='专题主持人')),
                ('background_url', models.CharField(max_length=200, null=True, verbose_name='专题背景图片链接')),
                ('portrait', models.CharField(max_length=200, null=True, verbose_name='专题头像链接')),
            ],
        ),
        migrations.AddField(
            model_name='microblog',
            name='special_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='microblog.SpecialSubject', verbose_name='关联专题'),
        ),
        migrations.AddField(
            model_name='mbimg',
            name='micro_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='microblog.MicroBlog', verbose_name='关联微博信息'),
        ),
        migrations.AddField(
            model_name='comment',
            name='micro_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='microblog.MicroBlog', verbose_name='关联微博信息'),
        ),
    ]
