# Generated by Django 2.1 on 2019-05-12 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='专题名称')),
                ('desc', models.CharField(max_length=300, null=True, verbose_name='专题描述')),
                ('midtext', models.CharField(max_length=100, null=True, verbose_name='专题阅读、讨论量')),
                ('downtext', models.CharField(max_length=100, null=True, verbose_name='专题主持人')),
                ('background_url', models.CharField(max_length=200, null=True, verbose_name='专题背景图片链接')),
                ('portrait', models.CharField(max_length=200, null=True, verbose_name='专题头像链接')),
            ],
        ),
        migrations.AddField(
            model_name='microblog',
            name='special_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='microblog.SpecialSubject', verbose_name='关联专题'),
        ),
    ]
