# Generated by Django 2.1 on 2019-05-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.CharField(max_length=50, verbose_name='微博评论时间'),
        ),
        migrations.AlterField(
            model_name='microblog',
            name='created_at',
            field=models.CharField(max_length=50, verbose_name='创建时间'),
        ),
    ]
