# Generated by Django 2.1 on 2019-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20190510_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=500, unique=True, verbose_name='微博评论内容'),
        ),
        migrations.AlterField(
            model_name='microblog',
            name='micro_blog_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='微博ID'),
        ),
    ]
