# Generated by Django 2.1 on 2019-05-13 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0002_auto_20190512_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialsubject',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='专题名称'),
        ),
    ]
