# Generated by Django 2.1 on 2019-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog', '0003_auto_20190510_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=500, verbose_name='微博评论内容'),
        ),
    ]
